<?php

// Basic settings
// You must set these for the server to work

$databaseServer = "localhost";
$databaseUsername = "testUser";
$databasePassword = "testPassword";
$databaseName = "test";

// The URL of to the server.php script.
$fullServerURL = "http://localhost/jcr13/novemberServer/server.php";

$terminalURL = "http://localhost/jcr13/ProjectNovember/index.html";



// End Basic settings



// Customization settings

// Adjust these to change the way the server  works.





// Prefix to use in table names (in case more than one application is using
// the same database).  Multiple tables are created (example: "log", "reviews",
//  and so on).
//
// If $tableNamePrefix is "test_" then the tables will be named
// "test_log" and "test_reviews" and son on.
//
// Thus, more than one server installation can use the same database
// (or the server can share a database with another application that uses
//  similar table names).
$tableNamePrefix = "novemberServer_";



$enableLog = 1;


// should web-based admin require yubikey two-factor authentication?
$enableYubikey = 1;

// 12-character Yubikey IDs, one list for each access password
// each list is a set of ids separated by :
// (there can be more than one Yubikey ID associated with each password)
$yubikeyIDs = array( "ccccccbjlfbi:ccccccbjnhjc:ccccccbjnhjn", "ccccccbjlfbi" );

// used for verifying response that comes back from yubico
// Note that these are working values, but because they are in a public
// repository, they are not secret and should be replaced with your own
// values (go here:  https://upgrade.yubico.com/getapikey/ )
$yubicoClientID = "9943";
$yubicoSecretKey = "rcGgz0rca1gqqsa/GDMwXFAHjWw=";


// For hashing admin passwords so that they don't appear in the clear
// in this file.
// You can change this to your own string so that password hashes in
// this file differ from hashes of the same passwords used elsewhere.
$passwordHashingPepper = "262f43f043031282c645d0eb352df723a3ddc88f";

// passwords are given as hashes below, computed by:
// hmac_sha1( $passwordHashingPepper,
//            hmac_sha1( $passwordHashingPepper, $password ) )
// Where $passwordHashingPepper is used as the hmac key.
// Client-side hashing sends the password to the server as:
//   hmac_sha1( $passwordHashingPepper, $password )
// The extra hash performed by the server prevents the hashes in
// this file from being used to login directly without knowing the actual
// password.

// For convenience, after setting a $passwordHashingPepper and chosing a
// password, hashes can be generated by invoking passwordHashUtility.php
// in your browser.

// default passwords that have been included as hashes below are:
// "secret" and "secret2"

// hashes of passwords for for web-based admin access
$accessPasswords = array( "8e409075ab35b161f6d2d57775e5efbee8d7b674",
                          "20e1883a3d63607b60677dca87b41e04316ffc63" );


// for assigning end-user pass word sequences
// replace this with your own secret string
$passWordSelectionSecret = "83e0b8ff3bcc5861efd17dcc1990424be0a9ae61";



// number of users shown per page in the browse view
$usersPerPage = 20;


$defaultPageCharMS = 10;


$defaultPageTextColor = "#FFFFFF";
$defaultPagePromptColor = "#FFFF00";


$humanTypedPrefix = "Human: ";

$aiBufferLimit = 2000;

// send keep-alive request every 15 minutes
// (ai server spins down after 30 minutes idle)
$aiKeepAliveIntervalSeconds = 15 * 60;


// used to generate AES key for encrypting user conversation buffers in
// the database
// replace this with your own secret string
$bufferEncryptionSecret = "3d8f9891437e8f8f42235c21a9e197f384bf3ea1";



// coreweave transformer URL
$coreWeaveURL = "http://put_your_url_here";


// replace with live secret from Stripe.
$stripeWebhookSecret = "whsec_DOAaOfi6oovfI9anrb6pSy3ofEF3uIWJ";

$fastSpringPrivateKey = "secret";


$creditsPerPenny = 3;


$creditPurchaseBonusMap = array( 1500 => 0,
                                 600 => 0,
                                 1200 => 100,
                                 2400 => 300,
                                 4800 => 700 );



$fastSpringTagCreditMap = array( "pn1500" => 1500,
                                 "pn600" => 600,
                                 "pn1200" => 1200,
                                 "pn2400" => 2400,
                                 "pn4800" => 4800 );





// SMTP settings

// if off, then raw sendmail is used instead 
$useSMTP = 0;

// SMTP requires that the PEAR Mail package is installed
// set the include path here for Mail.php, if needed:
/*
ini_set( 'include_path',
         ini_get( 'include_path' ) . PATH_SEPARATOR . '/home/jcr13/php' );
*/

$smtpHost = "ssl://mail.server.com";

$smtpPort = "465";

$smtpUsername = "jason@server.com";

$smtpPassword = "secret";



// separate SMTP for mission-critical, transactional emails (like download code
// emails)
// Defaults to being same as the above SMTP, which is used for bulk messages
//  (like a note sent to everyone).
$smtpHostTrans = $smtpHost;

$smtpPortTrans = $smtpPort;

$smtpUsernameTrans = $smtpUsername;

$smtpPasswordTrans = $smtpPassword;




?>